version: '3'


services:
  justina-db:
    container_name: justina_dev_database
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=justina_dev_db


